### ISSUE TITLE
Interactive Map Issues

### ISSUE THREAD

**Issue by Racquetballer** [AidanWelch/OpenTrafficCamMap#21]
When clicking on locations via the Interactive Map link all images appear broken.   I tested at 5:46pm MT.

` {
        "location": {
          "description": "US-40 @ CO-94 (LV)",
          "latitude": 38.869465,
          "longitude": -103.121025,
          "direction": "North"
        },
        "url": "https://www.cotrip.org/dimages/camera?imageURL=liveview/US40MM425North.jpg",
        "encoding": "JPEG",
        "format": "IMAGE_STREAM",
        "marked_for_review": false
      },`

Example: https://www.cotrip.org/dimages/camera?imageURL=liveview/US40MM425North.jpg

**Comment by AidanWelch** [comment]
Most of the URLs are out-of-date, I'm working on modernizing the scripts so that I can update the URLs daily.

**Comment by AidanWelch** [comment]
By the way if you want an updated list (with a new schema) you can clone the repo and run `index.mjs` but it's currently only updated to run a few of the compilation scripts.

**Comment by AidanWelch** [comment]
New data is now on the master branch!  All compilation scripts aren't ported yet, but I will now start on CI
